events {}

http {
    upstream auth_service {
        server auth_service:8000;
    }

    upstream user_service {
        server user_service:8000;
    }

    upstream project_service {
        server project_service:8000;
    }

    server {
        listen 80;

        # Auth service
        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User service
        location /user/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Project service
        location /project/ {
            proxy_pass http://project_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
